name: 'snowflake_workshop'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_packages"

models:
  +schema: dbt_schema 
  +database: my_dbt_project
  snowflake_workshop:
    staging:
      +materialized: view
      +snowflake_warehouse: pc_dbt_wh
    marts:
      +materialized: table
      +snowflake_warehouse: pc_dbt_wh_large
    customer_rev:
      +enabled: false